return {
    {
        { "\" Returns true if the color hex value is light", "vimLineComment", "NormalBg" },
    },
    {
        { "function",          "vimCommand",   "NormalBg" },
        { "! IsHexColorLight", "vimFunction",  "NormalBg" },
        { "(",                 "vimParenSep",  "NormalBg" },
        { "color",             "vimOperParen", "NormalBg" },
        { ")",                 "vimParenSep",  "NormalBg" },
        { " ",                 "vimFuncBody",  "NormalBg" },
        { "abort",             "vimIsCommand", "NormalBg" },
    },
    {
        { "  ",          "vimFuncBody",  "NormalBg" },
        { "let",         "vimLet",       "NormalBg" },
        { " ",           "vimFuncBody",  "NormalBg" },
        { "l:raw_color", "vimVar",       "NormalBg" },
        { " ",           "vimFuncBody",  "NormalBg" },
        { "=",           "vimOper",      "NormalBg" },
        { " ",           "vimFuncBody",  "NormalBg" },
        { "trim",        "vimFuncName",  "NormalBg" },
        { "(",           "vimParenSep",  "NormalBg" },
        { "a:color",     "vimFuncVar",   "NormalBg" },
        { ", ",          "vimOperParen", "NormalBg" },
        { "'#'",         "vimString",    "NormalBg" },
        { ")",           "vimParenSep",  "NormalBg" },
    },
    {
        { "  ", "vimFuncBody", "NormalBg" },
    },
    {
        { "  ",            "vimFuncBody",  "NormalBg" },
        { "let",           "vimLet",       "NormalBg" },
        { " ",             "vimFuncBody",  "NormalBg" },
        { "l:red",         "vimVar",       "NormalBg" },
        { " ",             "vimFuncBody",  "NormalBg" },
        { "=",             "vimOper",      "NormalBg" },
        { " ",             "vimFuncBody",  "NormalBg" },
        { "str2nr",        "vimFuncName",  "NormalBg" },
        { "(",             "vimParenSep",  "NormalBg" },
        { "substitute",    "vimSubst",     "NormalBg" },
        { "(",             "vimParenSep",  "NormalBg" },
        { "l:raw_color, ", "vimOperParen", "NormalBg" },
        { "'(.{2}).{4}'",  "vimString",    "NormalBg" },
        { ", ",            "vimOperParen", "NormalBg" },
        { "'1'",           "vimString",    "NormalBg" },
        { ", ",            "vimOperParen", "NormalBg" },
        { "'g'",           "vimString",    "NormalBg" },
        { ")",             "vimParenSep",  "NormalBg" },
        { ", ",            "vimFuncBody",  "NormalBg" },
        { "16",            "vimNumber",    "NormalBg" },
        { ")",             "vimParenSep",  "NormalBg" },
    },
    {
        { "  ",               "vimFuncBody",  "NormalBg" },
        { "let",              "vimLet",       "NormalBg" },
        { " ",                "vimFuncBody",  "NormalBg" },
        { "l:green",          "vimVar",       "NormalBg" },
        { " ",                "vimFuncBody",  "NormalBg" },
        { "=",                "vimOper",      "NormalBg" },
        { " ",                "vimFuncBody",  "NormalBg" },
        { "str2nr",           "vimFuncName",  "NormalBg" },
        { "(",                "vimParenSep",  "NormalBg" },
        { "substitute",       "vimSubst",     "NormalBg" },
        { "(",                "vimParenSep",  "NormalBg" },
        { "l:raw_color, ",    "vimOperParen", "NormalBg" },
        { "'.{2}(.{2}).{2}'", "vimString",    "NormalBg" },
        { ", ",               "vimOperParen", "NormalBg" },
        { "'1'",              "vimString",    "NormalBg" },
        { ", ",               "vimOperParen", "NormalBg" },
        { "'g'",              "vimString",    "NormalBg" },
        { ")",                "vimParenSep",  "NormalBg" },
        { ", ",               "vimFuncBody",  "NormalBg" },
        { "16",               "vimNumber",    "NormalBg" },
        { ")",                "vimParenSep",  "NormalBg" },
    },
    {
        { "  ",            "vimFuncBody",  "NormalBg" },
        { "let",           "vimLet",       "NormalBg" },
        { " ",             "vimFuncBody",  "NormalBg" },
        { "l:blue",        "vimVar",       "NormalBg" },
        { " ",             "vimFuncBody",  "NormalBg" },
        { "=",             "vimOper",      "NormalBg" },
        { " ",             "vimFuncBody",  "NormalBg" },
        { "str2nr",        "vimFuncName",  "NormalBg" },
        { "(",             "vimParenSep",  "NormalBg" },
        { "substitute",    "vimSubst",     "NormalBg" },
        { "(",             "vimParenSep",  "NormalBg" },
        { "l:raw_color, ", "vimOperParen", "NormalBg" },
        { "'.{4}(.{2})'",  "vimString",    "NormalBg" },
        { ", ",            "vimOperParen", "NormalBg" },
        { "'1'",           "vimString",    "NormalBg" },
        { ", ",            "vimOperParen", "NormalBg" },
        { "'g'",           "vimString",    "NormalBg" },
        { ")",             "vimParenSep",  "NormalBg" },
        { ", ",            "vimFuncBody",  "NormalBg" },
        { "16",            "vimNumber",    "NormalBg" },
        { ")",             "vimParenSep",  "NormalBg" },
    },
    {
        { "  ", "vimFuncBody", "NormalBg" },
    },
    {
        { "  ",           "vimFuncBody",  "NormalBg" },
        { "let",          "vimLet",       "NormalBg" },
        { " ",            "vimFuncBody",  "NormalBg" },
        { "l:brightness", "vimVar",       "NormalBg" },
        { " ",            "vimFuncBody",  "NormalBg" },
        { "=",            "vimOper",      "NormalBg" },
        { " ",            "vimFuncBody",  "NormalBg" },
        { "((",           "vimParenSep",  "NormalBg" },
        { "l:red * ",     "vimOperParen", "NormalBg" },
        { "299",          "vimNumber",    "NormalBg" },
        { ")",            "vimParenSep",  "NormalBg" },
        { " ",            "vimOperParen", "NormalBg" },
        { "+",            "vimOper",      "NormalBg" },
        { " ",            "vimOperParen", "NormalBg" },
        { "(",            "vimParenSep",  "NormalBg" },
        { "l:green * ",   "vimOperParen", "NormalBg" },
        { "587",          "vimNumber",    "NormalBg" },
        { ")",            "vimParenSep",  "NormalBg" },
        { " ",            "vimOperParen", "NormalBg" },
        { "+",            "vimOper",      "NormalBg" },
        { " ",            "vimOperParen", "NormalBg" },
        { "(",            "vimParenSep",  "NormalBg" },
        { "l:blue * ",    "vimOperParen", "NormalBg" },
        { "114",          "vimNumber",    "NormalBg" },
        { "))",           "vimParenSep",  "NormalBg" },
        { " / ",          "vimFuncBody",  "NormalBg" },
        { "1000",         "vimNumber",    "NormalBg" },
    },
    {
        { "  ", "vimFuncBody", "NormalBg" },
    },
    {
        { "  ",           "vimFuncBody", "NormalBg" },
        { "return",       "vimNotFunc",  "NormalBg" },
        { " ",            "vimFuncBody", "NormalBg" },
        { "l:brightness", "vimVar",      "NormalBg" },
        { " ",            "vimFuncBody", "NormalBg" },
        { ">",            "vimOper",     "NormalBg" },
        { " ",            "vimFuncBody", "NormalBg" },
        { "155",          "vimNumber",   "NormalBg" },
    },
    {
        { "endfunction", "vimCommand", "NormalBg" },
    },

}

