name: CI
on:
  schedule:
    - cron: "0 0 8 * *"
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-version: stable
      - name: Setup Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: nightly
      - name: Generate Color Schemes
        run: bash ./workflow_gen.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Generate Treesitter theme colors
        run: bash ./workflow_ts.sh
      - name: Generate non-treesitter theme colors
        run: bash ./workflow_nots.sh
      - name: Data file
        run: bash ./workflow_move.sh
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): generate color data"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
